# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'consultar.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from vistas.imagenes import images

class Ui_consultar(object):
    def setupUi(self, consultar):
        consultar.setObjectName("consultar")
        consultar.resize(386, 506)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/calendar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        consultar.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(consultar)
        self.label.setGeometry(QtCore.QRect(0, 90, 371, 20))
        self.label.setStyleSheet("font: 87 10pt \"Arial Black\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(consultar)
        self.label_4.setGeometry(QtCore.QRect(0, 60, 371, 20))
        self.label_4.setStyleSheet("font: 87 10pt \"Arial Black\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(consultar)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 391, 51))
        self.label_2.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0.391089 rgba(243, 243, 243, 133), stop:0.915842 rgba(165, 157, 153, 133));")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(consultar)
        self.label_3.setGeometry(QtCore.QRect(0, 50, 391, 461))
        self.label_3.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0.18408 rgba(245, 206, 166, 245), stop:0.970149 rgba(245, 170, 92, 245));")
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(consultar)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(10, 330, 361, 151))
        self.textEdit.setPlaceholderText("")
        self.textEdit.setObjectName("textEdit")
        self.label_6 = QtWidgets.QLabel(consultar)
        self.label_6.setGeometry(QtCore.QRect(320, 0, 51, 41))
        self.label_6.setStyleSheet("image: url(:/images/viewEvent.png);\n"
"")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(consultar)
        self.label_7.setGeometry(QtCore.QRect(0, 120, 371, 20))
        self.label_7.setStyleSheet("font: 87 10pt \"Arial Black\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.lbImagen = QtWidgets.QLabel(consultar)
        self.lbImagen.setGeometry(QtCore.QRect(50, 160, 271, 151))
        self.lbImagen.setStyleSheet("image: url(:/images/alta.png);")
        self.lbImagen.setText("")
        self.lbImagen.setObjectName("lbImagen")
        self.label_3.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.label_2.raise_()
        self.textEdit.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.lbImagen.raise_()

        self.retranslateUi(consultar)
        QtCore.QMetaObject.connectSlotsByName(consultar)

    def retranslateUi(self, consultar):
        _translate = QtCore.QCoreApplication.translate
        consultar.setWindowTitle(_translate("consultar", "Consultar"))
        self.label.setText(_translate("consultar", "Hacer el examen de algoritmia t.t"))
        self.label_4.setText(_translate("consultar", "Lunes - 9:00 am"))
        self.label_2.setText(_translate("consultar", "Tarea 1"))
        self.textEdit.setHtml(_translate("consultar", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">Realizar el examn a como de lugar :v</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.label_7.setText(_translate("consultar", "Prioridad: Alta"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    consultar = QtWidgets.QDialog()
    ui = Ui_consultar()
    ui.setupUi(consultar)
    consultar.show()
    sys.exit(app.exec_())
