# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crear.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from vistas.imagenes import images

class Ui_crear(object):
    def setupUi(self, crear):
        crear.setObjectName("crear")
        crear.resize(356, 414)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/calendar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        crear.setWindowIcon(icon)
        self.label_2 = QtWidgets.QLabel(crear)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 401, 51))
        self.label_2.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0.391089 rgba(243, 243, 243, 133), stop:0.915842 rgba(165, 157, 153, 133));")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(crear)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(0, 50, 401, 461))
        self.label_3.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0.391089 rgba(243, 243, 243, 133), stop:0.915842 rgba(165, 157, 153, 133));")
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(crear)
        self.label.setGeometry(QtCore.QRect(10, 70, 151, 16))
        self.label.setStyleSheet("font: 87 10pt \"Arial Black\";")
        self.label.setObjectName("label")
        self.textline_Tarea = QtWidgets.QLineEdit(crear)
        self.textline_Tarea.setGeometry(QtCore.QRect(10, 100, 241, 21))
        self.textline_Tarea.setObjectName("textline_Tarea")
        self.label_4 = QtWidgets.QLabel(crear)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 151, 16))
        self.label_4.setStyleSheet("font: 87 10pt \"Arial Black\";")
        self.label_4.setObjectName("label_4")
        self.comboBox_Dia = QtWidgets.QComboBox(crear)
        self.comboBox_Dia.setGeometry(QtCore.QRect(10, 160, 151, 22))
        self.comboBox_Dia.setObjectName("comboBox_Dia")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.label_5 = QtWidgets.QLabel(crear)
        self.label_5.setGeometry(QtCore.QRect(10, 200, 151, 16))
        self.label_5.setStyleSheet("font: 87 10pt \"Arial Black\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(crear)
        self.label_6.setGeometry(QtCore.QRect(190, 140, 151, 16))
        self.label_6.setStyleSheet("font: 87 10pt \"Arial Black\";")
        self.label_6.setObjectName("label_6")
        self.timeEdit_Hora = QtWidgets.QTimeEdit(crear)
        self.timeEdit_Hora.setGeometry(QtCore.QRect(190, 160, 118, 22))
        self.timeEdit_Hora.setObjectName("timeEdit_Hora")
        self.label_7 = QtWidgets.QLabel(crear)
        self.label_7.setGeometry(QtCore.QRect(10, 260, 151, 16))
        self.label_7.setStyleSheet("font: 87 10pt \"Arial Black\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(crear)
        self.label_8.setGeometry(QtCore.QRect(300, 0, 51, 41))
        self.label_8.setStyleSheet("image: url(:/images/addEvent.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.textEdit_Descripcion = QtWidgets.QTextEdit(crear)
        self.textEdit_Descripcion.setGeometry(QtCore.QRect(10, 280, 331, 87))
        self.textEdit_Descripcion.setObjectName("textEdit_Descripcion")
        self.comboBox_Prioridad = QtWidgets.QComboBox(crear)
        self.comboBox_Prioridad.setGeometry(QtCore.QRect(10, 220, 151, 22))
        self.comboBox_Prioridad.setObjectName("comboBox_Prioridad")
        self.comboBox_Prioridad.addItem("")
        self.comboBox_Prioridad.addItem("")
        self.comboBox_Prioridad.addItem("")
        self.comboBox_Prioridad.addItem("")
        self.pushButton_Guardar = QtWidgets.QPushButton(crear)
        self.pushButton_Guardar.setGeometry(QtCore.QRect(270, 390, 61, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Guardar.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Guardar.setIcon(icon1)
        self.pushButton_Guardar.setObjectName("pushButton_Guardar")

        self.retranslateUi(crear)
        QtCore.QMetaObject.connectSlotsByName(crear)

    def retranslateUi(self, crear):
        _translate = QtCore.QCoreApplication.translate
        crear.setWindowTitle(_translate("crear", "Registrar"))
        self.label_2.setText(_translate("crear", "Nueva tarea :)"))
        self.label.setText(_translate("crear", "Tarea:"))
        self.textline_Tarea.setPlaceholderText(_translate("crear", "Ingresa el nombre d ela tarea"))
        self.label_4.setText(_translate("crear", "Dia:"))
        self.comboBox_Dia.setItemText(0, _translate("crear", "Dia de la semana"))
        self.comboBox_Dia.setItemText(1, _translate("crear", "Lunes"))
        self.comboBox_Dia.setItemText(2, _translate("crear", "Martes"))
        self.comboBox_Dia.setItemText(3, _translate("crear", "Miercoles"))
        self.comboBox_Dia.setItemText(4, _translate("crear", "Jueves"))
        self.comboBox_Dia.setItemText(5, _translate("crear", "Viernes"))
        self.comboBox_Dia.setItemText(6, _translate("crear", "Sabado"))
        self.comboBox_Dia.setItemText(7, _translate("crear", "Domingo"))
        self.label_5.setText(_translate("crear", "Prioridad:"))
        self.label_6.setText(_translate("crear", "Hora:"))
        self.label_7.setText(_translate("crear", "Descripción"))
        self.comboBox_Prioridad.setItemText(0, _translate("crear", "--"))
        self.comboBox_Prioridad.setItemText(1, _translate("crear", "Alta"))
        self.comboBox_Prioridad.setItemText(2, _translate("crear", "Media"))
        self.comboBox_Prioridad.setItemText(3, _translate("crear", "Baja"))
        self.pushButton_Guardar.setText(_translate("crear", "Guardar"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    crear = QtWidgets.QDialog()
    ui = Ui_crear()
    ui.setupUi(crear)
    crear.show()
    sys.exit(app.exec_())
